### ISSUE TITLE
Question about comparison with Adversary AutoAugment in Table.3

### ISSUE THREAD

**Issue by Jackbrocp** [automl/trivialaugment#10]
Hi, 
I'm currently trying TA, and I find that following the experimental setup of Adv. AA, and TA can achieve further improvements.
So may I ask how you organize the experiments compared to Adv. AA?

**Comment by SamuelGabriel** [comment]
I don't quite understand your question. The scores are better in that comparison, because of the repeated batch setting, as you can see in this config for example: https://github.com/automl/trivialaugment/blob/master/confs/wresnet28x10_cifar10_b128_maxlr.1_weighteduniaug_w%3D0%2C1_widesesp_nowarmup_8timesbatch_200epochs.yaml

The important settings are:
```
all_workers_use_the_same_batches: true
gpus: 8
```

Does this answer your question?
